[project]
name = "manticore-manual"
version = "0.1.0"
description = "Add a short description here"
authors = ["Emmanuel Oga <contact@emmanueloga.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
msgspec = ">=0.18.6,<0.19"
rich = ">=13.7.1,<13.8"
pyyaml = ">=6.0.1,<6.1"
markdown = ">=3.6,<4"
pygments = ">=2.17.2,<2.18"
jinja2 = ">=3.1.3,<3.2"
